### ISSUE TITLE
HASS Add-on persisted data gets wiped on container restart?

### ISSUE THREAD

**Issue by madmachinations** [madmachinations/home-assistant-alexa-shopping-list#12]
HASS Add-on persisted data gets wiped on container restart

**Comment by madmachinations** [comment]
If someone could verify this for me please, that would be great. I don't have access to a HASS OS device.

**Comment by mmstano** [comment]
I can confirm. I did a hard reboot and it wiped my data and now I can’t get it to authenticate again. I’m very interested in getting this to work, so if there’s anything I can try to help make this better, let me know.

**Comment by madmachinations** [comment]
If you have a HASS OS device, are you able to please confirm what directories on the host are being mounted within the container?

https://gitlab.com/home-assistant-components/hass-addons/-/blob/main/alexa_shopping_list/config.yaml?ref_type=heads

It specifically requests a data directory be mounted and writeable, as described in the HASS docs; Which to my eyes looks correct? But perhaps I misread or misunderstood something?

Without a HASS device to validate what is going on there, or how the add-on config needs to be changed; This issue is basically stuck in the mud I'm afraid.

**Comment by mmstano** [comment]
I’m running HASS OS on a dell wyze mini PC. Where would I look to find this info? I’m rather tech savvy, but very much a copycat. I have Advanced SSH and Portainer add-on installed if those are tools that could help find the info we need. I’d just need to know the command/s for SSH or where to look in portainer. 

Or do I need to debug and check within the HASS or add-on logs within the OS itself?

**Comment by madmachinations** [comment]
Honestly off the top of my head I don't know I'm afraid.

I have about 1 weeks worth of HASS OS experience, which was several years ago and it properly chapped my ass. So I replaced it.

And that's kinda the problem because every OS has it's own esoteric idiosyncrasies and problems. HASS OS is also a container orchestration environment, which is doing things in it's own way.

And I don't have enough experience with it to know these things, perhaps someone with more HASS OS experience will appear and be able to offer some insights to us haha.

**Comment by mmstano** [comment]
I’ve inspected other add-ons config files and all of them list the directories under map as something like -

share:ro 
or
config:rw 

so I’m lead to assume that you list the directory with a colon and the permission

**Comment by madmachinations** [comment]
Hmmm, I have also had a look about.

Could you please try with the new configuration?

https://gitlab.com/home-assistant-components/hass-addons/-/blob/main/alexa_shopping_list/config.yaml

**Comment by mmstano** [comment]
I’m on mobile as of right now. When I get to my computer, I’ll give it a go

**Comment by mmstano** [comment]
I’m antsy, so I tried over mobile using the File Manager add-on and came across a hurdle within HASS OS’ idiosyncrasies. 

An add-ons config file resides within the add-ons container itself and there’s no simple way of accessing it. Did some digging and came across this https://community.home-assistant.io/t/silly-question-where-is-the-config-for-the-addons/307535/14

I can fiddle with Portainer when I get to my computer to see if I can access it there

**Comment by mmstano** [comment]
I’m probably overthinking that lol, I’ll try uninstalling and reinstalling it since it looks like you updated the gitlab

**Comment by madmachinations** [comment]
Haha there's no rush, it can definitely wait until you find yourself back in front of a computer 😝 .

And yea it should just be a case of removing the add on, and removing the gitlab repo link. Then adding it again like it was a fresh setup I guess?

**Comment by mmstano** [comment]
okay! Good news is the config file is persisting upon restarts. The bad news is I still can't authenticate (I've even logged into amazon.co.uk even though I'm in the US and it works for the browser but the add-on doesn't work). I'm getting a close frame error from the websocket no matter what servers I use. I'm thinking this is an Amazon issue because every time I login via browser, it redirects and wants me to create a passkey.

**Comment by mmstano** [comment]
Before, when I would restart the add-on, it would say invalid config and have me re-enter the server address. Upon restarts now, it says I have a valid config and goes straight to asking for username/password

**Comment by madmachinations** [comment]
Okay cool, thank you for confirming that. I'm going to close this issue and lets continue about your authentication within #10 please :)
