### ISSUE TITLE
HACS don't allow download

### ISSUE THREAD

**Issue by lein1013** [madmachinations/home-assistant-alexa-shopping-list#13]
great idea!  I've installed the Add-on and I've added the repository to HACS and it shows up correctly
![image](https://github.com/user-attachments/assets/8267a4ea-3a67-41a4-819e-7f91e0d2592b)

after pressing Download I get
![image](https://github.com/user-attachments/assets/ee9ce50a-d533-404d-9f0d-8099a3caa369)

Using HACS:

<html>
<body>

Integration version: | 2.0.1
-- | --
Frontend version: | 20240903140523
Repositories: | 1415
Downloaded repositories: | 14

</body>
</html>

**Comment by Mekki86** [comment]
The same for me. Have you solved it by any chance?
Thank you

**Comment by madmachinations** [comment]
I'm not sure off the top of my head, but I'm pretty sure that HACS requires specific files and configurations present within the repository for it to work. Unless that requirement has changed with HACS 2, since the last time I looked at it anyway.

**Comment by Mekki86** [comment]
forgive my ignorance, after putting the folder in /config/custom_components, what should I do?

**Comment by madmachinations** [comment]
> forgive my ignorance, after putting the folder in /config/custom_components, what should I do?

No worries. So you should have `/config/custom_components/alexa_shopping_list` yisssss? If you do, just restart home assistant.

Then go to settings > devices & integrations > add integration = and search for alexa shopping list, click that and the component setup will start.

**Comment by Mekki86** [comment]
My mistake was putting the entire github folder in custom_components and not just the alexa_shopping_list folder.
Now it works. Tanks a lot

**Comment by madmachinations** [comment]
> My mistake was putting the entire github folder in custom_components and not just the alexa_shopping_list folder. Now it works. Tanks a lot

No problem, good luck! :)

**Comment by mekki1986** [comment]
I'm sorry, but I cheered too soon! 
The server works, calling the list from the command line returns me correctly, but I can't get the integration to work. The status is always unknown and does not update the list in HA. The IP address is correct, I haven't changed the port so I assume it is always 4000. 
What could be the problem?
Maybe the Client folder was to be copied to a specific place?

**Comment by madmachinations** [comment]
> I'm sorry, but I cheered too soon! The server works, calling the list from the command line returns me correctly, but I can't get the integration to work. The status is always unknown and does not update the list in HA. The IP address is correct, I haven't changed the port so I assume it is always 4000. What could be the problem? Maybe the Client folder was to be copied to a specific place?

Are you using HASS OS by any chance?

**Comment by mekki1986** [comment]
Yes! 🤔

**Comment by madmachinations** [comment]
I've heard this from other people using HASS OS also. I'll open an issue for it. I have no idea what is wrong, I can only assume HASS OS isn't installing something the custom component needs

**Comment by madmachinations** [comment]
New issue is here:

https://github.com/madmachinations/home-assistant-alexa-shopping-list/issues/14

**Comment by madmachinations** [comment]
You can try downloading the component with hacs now @lein1013 @mekki1986

**Comment by lein1013** [comment]
> You can try downloading the component with hacs now @lein1013 @mekki1986

Looks good - could now download it
![grafik](https://github.com/user-attachments/assets/14d1d3d4-81e2-40b3-9610-8b3ea4da080b)

custom config is now in the custom_components folder. 
When adding the integration, I can not connect
![grafik](https://github.com/user-attachments/assets/e58d0979-7090-404d-99b2-4bb7efb8fbdc)

Addon is running, but there are no logs of the Addon (version 2409.259)

**Comment by madmachinations** [comment]
> > You can try downloading the component with hacs now @lein1013 @mekki1986
> 
> Looks good - could now download it ![grafik](https://private-user-images.githubusercontent.com/72338417/371850950-14d1d3d4-81e2-40b3-9610-8b3ea4da080b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4NzMxODgsIm5iZiI6MTcyNzg3Mjg4OCwicGF0aCI6Ii83MjMzODQxNy8zNzE4NTA5NTAtMTRkMWQzZDQtODFlMi00MGIzLTk2MTAtOGIzZWE0ZGEwODBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAyVDEyNDEyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5MDJiZWNhYTMyZWU2NWUyZDQxYjZkMWM2NGY1ZDJjZjJhOGFiYWEwMjM4YTY1ZWI0OTM0NjljYzVkY2Y4MjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bwMJ7tqj-Q69XVX4yPVGG4S9WSzHJOP8eB8uWdBnk1U)
> 
> custom config is now in the custom_components folder. When adding the integration, I can not connect ![grafik](https://private-user-images.githubusercontent.com/72338417/371852677-e58d0979-7090-404d-99b2-4bb7efb8fbdc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4NzMxODgsIm5iZiI6MTcyNzg3Mjg4OCwicGF0aCI6Ii83MjMzODQxNy8zNzE4NTI2NzctZTU4ZDA5NzktNzA5MC00MDRkLTk5YjItNGJiN2VmYjhmYmRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAyVDEyNDEyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0YjU5NzkzNTI1YzEyN2VlZTg1ZjJmYTQxNjI0NjdmODZlNzgyZWY2OTFhNDBjMDFhNzliMGJjNGRiNTc2MWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vUPyH-guAupKvaGya5csHaFziL4Q8vx7ojoYT-0aDic)
> 
> Addon is running, but there are no logs of the Addon (version 2409.259)

Ahhh amazing, thank you for checking it and that the component now downloads and installs via HACS.

But yea, the component is just one part of this integration. It needs the server setting up, which HACS cannot handle. If you are using HASS OS there is an add-on for the server part. If not, and either way, there are setup instructions for the server in this projects README.md file.

Thanks again.
