### ISSUE TITLE
Server thinks it's authenticated when it isn't after a period of inactivity

### ISSUE THREAD

**Issue by madmachinations** [madmachinations/home-assistant-alexa-shopping-list#16]
Server thinks it's authenticated when it isn't after a period of inactivity

**Comment by mekki1986** [comment]
I uninstalled the server that I had installed via hacs and removed the folders in custom_components and client. I reinstalled it but it doesn't ask me to authenticate. So there are other files that maintain it, but I can't find them. Where can they be?

**Comment by madmachinations** [comment]
> I uninstalled the server that I had installed via hacs and removed the folders in custom_components and client. I reinstalled it but it doesn't ask me to authenticate. So there are other files that maintain it, but I can't find them. Where can they be?

I'm not sure where HASS stores them, but when you install the HASS Add-on it tells HASS it wants a folder somewhere that it can keep permanent files.

A quick google tells me there should be a folder, probably called alexa_shopping_list, in here:

`/mnt/data/supervisor/addons/data/`

Delete that folder and start up the server again, and it should be a fresh install from that point

**Comment by mekki1986** [comment]
I'm sorry, I can't find the file. I tried in every way, from terminal, with samba with file editor, but I don't have any folders with that name.
Unfortunately I will have to give up the integration.
Thanks anyway for your work

**Comment by KiraPC** [comment]
When you get the token from the browser, can you open it and check the expiration date?

**Comment by moryoav** [comment]
I'm having a similar problem, or similar to the other issue reported here, I'm not sure.
I did step #2 in the guide, and used the amazon.uk server. I then realized (it should be clarified in the readme) that Amazon has separate shopping lists for every site, and I was using the .com one for my lists. So my .uk shopping list was empty (maybe that's an issue users are experiencing not realizing this is the case). I then had no way to change my credentials to the .com site, or at least I couldn't figure out how to do it. So I uninstalled the server and re-installed it, thinking I could now do step #2 again and re-do the authentication process. However now I get the situation where it tells me (I was not given the option to re-authenticate, contrary to what I thought would happen):
```
Checking config
Config is valid

Checking authentication
Server is authenticated
```
And then when I do "list" it tells me ERROR: Not authenticated.

I cannot find where the server stores the data files in Home Assistant (Installed through HACS). 
It would be great if among the other command line options, I would have a command to "reauthenticate" which will allow me to just do it again.

**Comment by madmachinations** [comment]
> I'm having a similar problem, or similar to the other issue reported here, I'm not sure. I did step #2 in the guide, and used the amazon.uk server. I then realized (it should be clarified in the readme) that Amazon has separate shopping lists for every site, and I was using the .com one for my lists. So my .uk shopping list was empty (maybe that's an issue users are experiencing not realizing this is the case). I then had no way to change my credentials to the .com site, or at least I couldn't figure out how to do it. So I uninstalled the server and re-installed it, thinking I could now do step #2 again and re-do the authentication process. However now I get the situation where it tells me (I was not given the option to re-authenticate, contrary to what I thought would happen):
> 
> ```
> Checking config
> Config is valid
> 
> Checking authentication
> Server is authenticated
> ```
> 
> And then when I do "list" it tells me ERROR: Not authenticated.
> 
> I cannot find where the server stores the data files in Home Assistant (Installed through HACS). It would be great if among the other command line options, I would have a command to "reauthenticate" which will allow me to just do it again.

I will add a command to reset the server config, in the mean time:

Did you mean you installed through HASS or through HACS? Because HACS doesn't have the server, it only has the HA component, and that install method is completely untested. So I assume you mean HASS?

If that is the case, on your HASS OS device, please can you look in:

`usr/share/hassio/addons/`

and see if there is an `alexa_shopping_list`, or similar, folder in there?

If there is, is there a `data` folder inside that? If so, delete everything in the `data` folder and restart the server.

**Comment by moryoav** [comment]
> Did you mean you installed through HASS or through HACS? Because HACS doesn't have the server, it only has the HA component, and that install method is completely untested. So I assume you mean HASS?
> 
> If that is the case, on your HASS OS device, please can you look in:
> 
> `usr/share/hassio/addons/`
> 
> and see if there is an `alexa_shopping_list`, or similar, folder in there?
> 
> If there is, is there a `data` folder inside that? If so, delete everything in the `data` folder and restart the server.

Yeah, my mistake, I meant I installed the addon regularly as HASS addon (as the readme suggested, from https://gitlab.com/home-assistant-components/hass-addons)
And yes, I'm on Home Assistant OS device.
However, in /usr/share I have no hassio folder. If I do "find / -name "addons" I find two such folders (one /root/addons and the other /addons), they're both empty.

**Comment by madmachinations** [comment]
> > Did you mean you installed through HASS or through HACS? Because HACS doesn't have the server, it only has the HA component, and that install method is completely untested. So I assume you mean HASS?
> > If that is the case, on your HASS OS device, please can you look in:
> > `usr/share/hassio/addons/`
> > and see if there is an `alexa_shopping_list`, or similar, folder in there?
> > If there is, is there a `data` folder inside that? If so, delete everything in the `data` folder and restart the server.
> 
> Yeah, my mistake, I meant I installed the addon regularly as HASS addon (as the readme suggested, from https://gitlab.com/home-assistant-components/hass-addons) And yes, I'm on Home Assistant OS device. However, in /usr/share I have no hassio folder. If I do "find / -name "addons" I find two such folders (one /root/addons and the other /addons), they're both empty.

Hmmm, I'm sorry I have no idea where HASS OS puts addon persistent storage. The documentation for it is pretty useless in that regard tbh. And I don't have a HASS OS device to have a look around and see, so I'm blind. I will add a reset command this evening

**Comment by moryoav** [comment]
And I'll just add that I saw in the config folder two files, config.json and a cookies file, I deleted both files and restarted the server, and now only the config.json gets created and not the cookies file, for some reason. And I get the error above. Maybe this is no longer relevant to this github issue, not sure anymore.

**Comment by madmachinations** [comment]
> And I'll just add that I saw in the config folder two files, config.json and a cookies file, I deleted both files and restarted the server, and now only the config.json gets created and not the cookies file, for some reason. And I get the error above. Maybe this is no longer relevant to this github issue, not sure anymore.

So I can't be sure, but it sounds like you still had the client running while you were deleting, and after having deleted, the server's file cache.

The client only asks the server if it has it's shit together and can do the do when it first opens and makes a connection with the server. So if you killed the client and re-ran it, it should have launched into the first run setup again, if you had deleted the server's cache and restarted it.

A new version of the server container is on docker hub now, if you update your server to this version and you download the new client from this repository, you should have access to a `reset` command.

This reset command just tells the server to delete it's file cache, and it causes the client to run the setup process again having done so.
