### ISSUE TITLE
new "reset" command, doesn't re-ask for username and password

### ISSUE THREAD

**Issue by moryoav** [madmachinations/home-assistant-alexa-shopping-list#18]
Image 1 is me logging in with amazon.co.uk, as a completely fresh install.
I am able to authenticate and get my uk shopping list.
Then I do "reset", it asks me for the new URL, and then I try the amazon.com domain.
It then does not ask me for username and password again.

So I thought maybe I don't need to be in the same session. I close the session and reopen it and that's image #2.
Again, no matter what I do, it will not ask me for the credentials again for the .com website.

Even if I do complete fresh install and this time I choose the amazon.com website as the first thing I try, then it also doesn't ask me for credentials again. Just says server is authenticated. Not sure what's going on... (so I started a new GitHub ticket, I hope it's ok)

![Capture1](https://github.com/user-attachments/assets/2c9f056c-a6d1-4766-bc2a-0d1e73ba140e)
![Capture2](https://github.com/user-attachments/assets/24e752a0-7203-4abc-b163-d9a4c7849873)

**Comment by madmachinations** [comment]
If you do a reset and instead of switching to amazon.com, you stick with amazon.co.uk - does it ask you to login then?

Because either it's holding onto a cached bit of information somewhere that is slipping my mind, or it is something specific to US amazon, which has presented lots of other problems because it's different ( #10 )

**Comment by moryoav** [comment]
If I stick with amazon.co.uk then it works fine every single time. I can reset time and time again, it asks for credentials, and works fine every time. However if I try amazon.com, no matter what I do, it tells me that I'm authenticated, doesn't ask for my username and password and then doesn't let me do "list", saying it's not authenticated. So this is turning out to be something very specific to the amazon.com authentication process. I'd love to help debug this, if you need any help here.

**Comment by madmachinations** [comment]
> If I stick with amazon.co.uk then it works fine every single time. I can reset time and time again, it asks for credentials, and works fine every time. However if I try amazon.com, no matter what I do, it tells me that I'm authenticated, doesn't ask for my username and password and then doesn't let me do "list", saying it's not authenticated. So this is turning out to be something very specific to the amazon.com authentication process. I'd love to help debug this, if you need any help here.

Ah! Okay then that's definitely a problem specific to the US amazon then.

In that case I'm going to close this issue, and reference it in #10 , and continue working this problem in there :)

Any help you can provide would be greatly appreciated. My time is limited at the moment and it will be a couple of weeks I imagine before I find the time to sit and work out what is different specifically about the US version, and what changes need to be made so it can work
