### ISSUE TITLE
HASS Addon

### ISSUE THREAD

**Issue by madmachinations** [madmachinations/home-assistant-alexa-shopping-list#9]
Perhaps the server can be made available as a HASS addon.

**Comment by KiraPC** [comment]
Hello,

I've installed the add-on, started then installed the integration, when I try to configure it I receive the error "Sync server has not been configured, please set it up first."

Do I have to configure the add-on? And how?

Thanks :)

**Comment by madmachinations** [comment]
Hello,

Yea installation is done in three main steps:

1) Install the server somehow with either the HASS Addon, or a docker container, or setting it up manually
2) Configure the server with the client script
3) Add the custom component to your HA installation

Sounds like you have done steps 1 and 3, but not 2. The documentation for which is here:

https://github.com/madmachinations/home-assistant-alexa-shopping-list?tab=readme-ov-file#step-2---configure-the-server

Fair warning, if you are in the US, this won't be working for you at the moment. There is another issue open where I need to write drivers specifically for the US version of amazon. But I haven't finished that up yet. That issue is here in case this affects you and you want to follow it  #10 

So far I only know for certain that it is working with british amazon and I think australian amazon also. All other regions are completely untested and just work in theory.

Once the server is configured, you should be able to type 'list' in the client and see what is currently on your alexa shopping list. If it comes back empty and there are definitely things on your shopping list, then please open another issue for your region and let me know what version of the amazon site you are accessing it through.

Good luck!

**Comment by KiraPC** [comment]
mmm, so the client script is not bundled inside the add-on? I searched for it but couldn't find it.

I'm from IT, I'll your tester for this region :)

**Comment by madmachinations** [comment]
The client script isn't in the add on no, it's in this github repository. You need to download all the files from here and then there is a "client" folder with a "client.py" script inside it.

**The server / add-on**

So the add-on is a small piece of software that talks to the amazon website, and provides some commands that other stuff can use to get the shopping list, add stuff to it, etc. It doesn't do anything else other than this.

In order to talk to your shopping list, it has to be logged into your amazon account. But this isn't a straight forward process because of the MFA code they send to you when you login to a new place.

**The client**

The client is a small script you run on the laptop/pc/whatever you are currently sat typing on. It does not run on your home assistant device.

This lets you sit at your laptop, connect into the server add-on, and log it into your amazon account.

You should only have to run this once. Once you are done with it, you don't need to use the client anymore unless you want to talk directly to the server add-on.

**The HA component**

The component is just like the client, but specifically for home assistant to use.

It doesn't know how to login, so it expects the server add-on is already logged in and ready to go. The component talks to the server add-on in the same way the client script does. Except it is only interested in getting what is currently on the shopping list, adding missing things to it, removing things you ticked off already in your HA shopping list... etc.

And it uses those commands and data to keep both lists in sync.

**Comment by madmachinations** [comment]
If you go to the main page in this repository, the code tab, and then there is a big green Code button. Press that and there will be an option to "Download ZIP". That will give you all the files that are in this project, one of which is the client

**Comment by KiraPC** [comment]
Oh no problem.

I just cloned the repo. I'm a dev not worry about tech stuff.

I run the script in the container and auth was ok, but when I try the list command it log "ERROR: Not authenticated" even if after the "login" process it says "Server is authenticated" and the cookie file is populated.

**Comment by KiraPC** [comment]
I suppose there is something different inside the amazon.it webpage.

selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[name="rememberMe"]"}

**Comment by madmachinations** [comment]
Interesting! Okay I'm gonna open a new issue for italy and tag you in there

**Comment by KiraPC** [comment]
Yes :)

**Comment by madmachinations** [comment]
Okay new issue is here if you could please check it out and try the login :)

https://github.com/madmachinations/home-assistant-alexa-shopping-list/issues/11
